#!/bin/bash
# License: https://creativecommons.org/publicdomain/zero/1.0/

readonly CFOLDER=/etc/wireguard/clients
readonly THISFILE=$(basename $0)

# =================================================

main () {
  # Check for root privileges
  [[ $USER == root ]] || { echo "Root privileges required. Try: sudo $THISFILE"; return 1; }

  # Find Wireguard interface
  if=$(wg show interfaces)
  [[ $if =~ ' ' ]] && { echo "WARNING: multiple Wireguard interfaces detected"; }
  read -r INTERFACE rest <<<$if; readonly INTERFACE
  echo "Using interface $INTERFACE"

  case $1 in
    a*)
      add_new_peer "$2"
      ;;
    s*)
      show_peer_conf $2
      ;;
    d*)
      shift
      delete_peer $@
      ;;
    l*)
      list_peers
      ;;
    f*)
      fix_config_names
      ;;
    *)
      usage
      ;;
  esac
}

# =================================================

usage () {
cat <<USAGE
$THISFILE [add [<desc>]|show <peer>|del <peer> ...|list|fix]

a[dd]  : add a new peer
s[how] : show peer configuration
d[el]  : delete peer(s)
l[ist] : list peers
f[ix]  : rename old style client config files to new (based on client public key)
<desc> is an optional mnemonic peer description, e.g. "John Doe phone". Default is the peer public key.
<peer> is the peer public key as shown by list command
USAGE
}

sanitize_pk () {
  local pk=$1
  tr '/+' '.-' <<<${pk:0:-1}
  # https://lists.zx2c4.com/pipermail/wireguard/2020-December/006222.html
}

fix_config_names () {
  local f pk g
  cd $CFOLDER || { echo "Cannot access $CFOLDER"; return 1; }
  echo "Fixing file names in $CFOLDER"
  for f in *; do
    pk=$(wg pubkey <<<$(awk -F ' *= *' '/^PrivateKey/{print $2"=";exit}' $f)) || {
      echo "PrivateKey not found in $f"
      continue
    }
    g=$(sanitize_pk $pk)
    [[ $f == $g ]] && continue
    mv -v $f $g
  done
}

build_peer_list () {
  PEERLIST=':'$(wg show $INTERFACE peers | awk '{printf $1":"}')
}

check_peer_exists () {
  local pk=$1
  build_peer_list
  [[ $PEERLIST =~ ":${pk}:" ]] || { echo "Cannot find peer $pk"; return 1; }
}

show_peer_conf () {
  local pk=$1
  check_peer_exists $pk || return 1
  local clientfile=$CFOLDER/$(sanitize_pk $pk)
  [[ -r $clientfile ]] || { echo "Cannot read $clientfile"; return 1; }
  qrencode -t ANSIUTF8 < $clientfile
  cat $clientfile
  echo -e "---------\n"
  wg show $INTERFACE | awk '$0=="peer: '${pk}'"{f=1; print; next} /^peer:/{f=0} f'
}

delete_peer () {
  local pk
  for pk in $@
  do
    check_peer_exists $pk || continue
    wg set $INTERFACE peer $pk remove && {
      wg-quick save ${INTERFACE}
      clientfile=$CFOLDER/$(sanitize_pk $pk)
      rm -f $clientfile
      echo "Removed peer $pk"
    } || { echo "Cannot remove peer $pk"; return 1; }
  done
}

list_peers () {
  local a b clientfile x y
  while read -r a b
  do
    if [[ $a == 'peer:' ]]
    then
      echo -n '-- '
      clientfile=$CFOLDER/$(sanitize_pk $b)
      read x y < <(head -n1 $clientfile)
      [[ $x == '#' ]] && echo $y || echo
      echo "# $THISFILE show '$b'"
      echo "# $THISFILE del '$b'"
    fi
    echo "$a $b"
  done < <(wg show $INTERFACE)
}

add_new_peer () {
  local readonly desc=$1
  # Generate peer keys
  PRIVATE_KEY=$(wg genkey)
  PUBLIC_KEY=$(echo ${PRIVATE_KEY} | wg pubkey)
  PRESHARED_KEY=$(wg genpsk)

  # Read server key from interface
  SERVER_PUBLIC_KEY=$(wg show ${INTERFACE} public-key)

  # Get next free peer IP (This will break after x.x.x.255)
  PEER_ADDRESS=$(wg show ${INTERFACE} allowed-ips)
  if [[ $PEER_ADDRESS ]]
  then
    PEER_ADDRESS=$(
      grep -oP '([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}' <<<"$PEER_ADDRESS" |
      awk -F'[./]' '{print $1"."$2"."$3"."1+$4"/"$5}' |\
      sort -t '.' -k 1,1 -k 2,2 -k 3,3 -k 4,4 -n | tail -n1)
  else
    PEER_ADDRESS=$(
      jq -j '.[0].addr_info[0].local|split(".")|.[0]+"."+.[1]+"."+.[2]+"."+(.[3]|tonumber+1|tostring)' \
        <(ip -4 -j address show ${INTERFACE}))
  fi

  # Try to guess nameserver
  NAMESERVER=$(ip -j addr show $INTERFACE | jq -r '.[0].addr_info[0].local')
  nslookup google.com $NAMESERVER > /dev/null || {
    NAMESERVER=$(nslookup bogusname | awk '/^Server:/{print $2}')
    [[ ! $NAMESERVER =~ ^127 ]] && nslookup google.com $NAMESERVER > /dev/null || NAMESERVER="8.8.8.8, 1.1.1.1"
  }
  echo "Guessed nameserver: $NAMESERVER"

  LISTENPORT=$(wg show ${INTERFACE} listen-port)
  ENDPOINT=$(curl -s ipinfo.io | jq -r '.ip')

  # Add peer
  wg set ${INTERFACE} peer ${PUBLIC_KEY} preshared-key <(echo ${PRESHARED_KEY}) allowed-ips ${PEER_ADDRESS} || {
    echo "Cannot add peer ${PEER_ADDRESS} with public key ${PUBLIC_KEY}"
    return 1
  }
  wg-quick save ${INTERFACE}

  # Generate peer config
  read -r -d$'\x04' CONFIG << END_OF_CONFIG
# ${desc:-${PUBLIC_KEY}}
[Interface]
Address = ${PEER_ADDRESS}
PrivateKey = ${PRIVATE_KEY}
DNS = ${NAMESERVER}

[Peer]
PublicKey = ${SERVER_PUBLIC_KEY}
PresharedKey = ${PRESHARED_KEY}
AllowedIPs = 0.0.0.0/1, 128.0.0.0/1
Endpoint = ${ENDPOINT}:${LISTENPORT}
END_OF_CONFIG

  # Save added peer config
  clientfile=$CFOLDER/$(sanitize_pk $PUBLIC_KEY)
  mkdir -p $CFOLDER
  touch $clientfile
  chmod go-rwx $clientfile
  echo "$CONFIG" >${clientfile}

  # Show added peer config
  show_peer_conf ${PUBLIC_KEY}
}

# =================================================

main "$@"
